# generated by duploctl pipeline, do no edit
class Duploctl < Formula
  desc "Command-line tools for Duplocloud"
  homepage "https://github.com/duplocloud/duploctl"
  version "0.2.13"
  license "MIT"
  base_url = "#{homepage}/releases/download/v#{version}/duploctl-#{version}"

  on_macos do
    url "#{base_url}-darwin-amd64.tar.gz"
    sha256 "e0c9b3ff90c1a4539be7b5ba102d3c65b0d661f1ce48232697d9aee118f79097"
  end

  on_linux do
    url "#{base_url}-linux-amd64.tar.gz"
    sha256 "37928fadf0964168d1fd8231d7221347026915f2f830263bbb9b87e61394653b"
  end

  def install
    bin.install "duploctl"
  end

  test do
    system "duploctl --version"
  end
end
