# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DuploJit < Formula
  desc "Command-line tools for JIT Duplo, AWS and Kubernetes access"
  homepage "https://github.com/duplocloud/duplo-jit"
  version "0.5.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/duplocloud/duplo-jit/releases/download/v0.5.6/duplo-jit_0.5.6_darwin_amd64.zip"
      sha256 "44ca56de54820129ee1bbe1b6b4ee340bfbbfad520302a8271ea66b776c07487"

      def install
        bin.install "duplo-aws-credential-process"
        bin.install "duplo-jit"
      end
    end
    on_arm do
      url "https://github.com/duplocloud/duplo-jit/releases/download/v0.5.6/duplo-jit_0.5.6_darwin_arm64.zip"
      sha256 "e1e6e93509c403496583b87d28add3de66b7342001504f5faf322957a96ed8cb"

      def install
        bin.install "duplo-aws-credential-process"
        bin.install "duplo-jit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/duplocloud/duplo-jit/releases/download/v0.5.6/duplo-jit_0.5.6_linux_amd64.zip"
        sha256 "6962646c03efc3ab1e9c72c26925f29514425c85c542cd0221415b6925fdcb24"

        def install
          bin.install "duplo-aws-credential-process"
          bin.install "duplo-jit"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/duplocloud/duplo-jit/releases/download/v0.5.6/duplo-jit_0.5.6_linux_arm.zip"
        sha256 "a2939fb103c1a0db9fe839907de887982cbaa43b49ae5da7a9df87c2e5eab78b"

        def install
          bin.install "duplo-aws-credential-process"
          bin.install "duplo-jit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/duplocloud/duplo-jit/releases/download/v0.5.6/duplo-jit_0.5.6_linux_arm64.zip"
        sha256 "4606e86c195b5d39025bf9bb0748c1664b4dbd1b551c8bb71e96448efa4e47d9"

        def install
          bin.install "duplo-aws-credential-process"
          bin.install "duplo-jit"
        end
      end
    end
  end

  test do
    system "duplo-jit version"
  end
end
