# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DuploJit < Formula
  desc "Command-line tools for JIT Duplo, AWS and Kubernetes access"
  homepage "https://github.com/duplocloud/duplo-jit"
  version "0.5.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/duplocloud/duplo-jit/releases/download/v0.5.8/duplo-jit_0.5.8_darwin_amd64.zip"
      sha256 "004941aa94f342c0f2cc71cddd872e9cf7a38ced2d5df59418001256e0ca85fb"

      def install
        bin.install "duplo-aws-credential-process"
        bin.install "duplo-jit"
      end
    end
    on_arm do
      url "https://github.com/duplocloud/duplo-jit/releases/download/v0.5.8/duplo-jit_0.5.8_darwin_arm64.zip"
      sha256 "43f8ef9934bbf694f9addd8e992452eee3b51bc0563b08036e1d6116d47f4e70"

      def install
        bin.install "duplo-aws-credential-process"
        bin.install "duplo-jit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/duplocloud/duplo-jit/releases/download/v0.5.8/duplo-jit_0.5.8_linux_amd64.zip"
        sha256 "52bab790b79bc0312ecf74e9d50aeec1049fb4e1329e58ba15da12889cb0470a"

        def install
          bin.install "duplo-aws-credential-process"
          bin.install "duplo-jit"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/duplocloud/duplo-jit/releases/download/v0.5.8/duplo-jit_0.5.8_linux_arm.zip"
        sha256 "beaa5295e2b43324bd09ae8d6dc0cced53a27910d7380d86950675c635565df8"

        def install
          bin.install "duplo-aws-credential-process"
          bin.install "duplo-jit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/duplocloud/duplo-jit/releases/download/v0.5.8/duplo-jit_0.5.8_linux_arm64.zip"
        sha256 "c31103c76d3b48aa03d01fab91d379a35be7fc261b1a4faade902c020eddf561"

        def install
          bin.install "duplo-aws-credential-process"
          bin.install "duplo-jit"
        end
      end
    end
  end

  test do
    system "duplo-jit version"
  end
end
